on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    name: laz-perf (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
          #        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        os: ['ubuntu-latest']
        python-version: ['3.8']
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1.1.2
        with:
          channels: conda-forge,spyder-ide
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Setup
        shell: bash -l {0}
        run: |
            conda install compilers cmake -y
            conda install laz-perf --only-deps -y
            pwd
            mkdir build
            ls
      - name: Configure
        working-directory: ./build
        shell: bash -l {0}
        run: |
            pwd
            ls
            cmake .
      - name: Build
        shell: bash -l {0}
        working-directory: ./build
        run: |
            make
      - name: Test
        shell: bash -l {0}
        run: |
            ctest



