on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    name: laz-perf (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.7','3.8']
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1.1.2
        with:
          channels: conda-forge,defaults
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Setup
        shell: bash -l {0}
        run: |
            conda install -c conda-forge ninja pytest cython numpy compilers cmake -y
            conda install laz-perf --only-deps -y
            pwd
            ls
      - name: Configure
        shell: bash -l {0}
        run: |
            pwd
            ls
            cmake . -G Ninja
      - name: Build
        shell: bash -l {0}
        run: |
            ninja
      - name: Test
        shell: bash -l {0}
        run: |
            ctest
      - name: Python
        shell: bash -l {0}
        run: |
            pip install -e .
        working-directory: ./python
      - name: Python Test
        shell: bash -l {0}
        run: |
            pytest
        working-directory: ./python



